# Generated by Django 4.2.4 on 2023-08-24 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomings',
            name='balance',
            field=models.FloatField(null=True, verbose_name='Баланс'),
        ),
        migrations.AddField(
            model_name='incomings',
            name='bank',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='incomings',
            name='pay',
            field=models.FloatField(default=0, verbose_name='Платеж'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incomings',
            name='response_date',
            field=models.DateTimeField(null=True, verbose_name='Распознанное время'),
        ),
        migrations.AddField(
            model_name='incomings',
            name='sender',
            field=models.CharField(max_length=50, null=True, verbose_name='Отравитель/карта'),
        ),
        migrations.AddField(
            model_name='incomings',
            name='transaction',
            field=models.CharField(max_length=30, null=True, verbose_name='Транзакция'),
        ),
        migrations.AddField(
            model_name='incomings',
            name='type',
            field=models.CharField(default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='incomings',
            name='register_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Время добавления в базу'),
        ),
    ]
