version: '3'

services:
  db_postgres:
    container_name: ftp_grabber
    build: .
    env_file: .env
    volumes:
      - ./logs:/app/logs
    ports:
      - "$FTP_PORT:$FTP_PORT"
    restart: always

