version: '3'

services:
  ftp_grabber:
    container_name: ftp_grabber
    build: .
    env_file: .env
    volumes:
      - ./logs/ftp_grabber:/app/logs
      - ./screenshots:/app/screenshots
    ports:
      - "$FTP_PORT:$FTP_PORT"
    restart: always

