version: '3.7'

services:
  grabber:
    container_name: adb_grabber
    build: .
    env_file: .env
    command: python3 adb_grabber.py
    privileged: true
    volumes:
      - ./logs/ftp_grabber:/app/logs
      - ./screenshots:/app/screenshots
    environment:
      - ANDROID_ADB_SERVER_ADDRESS=host.docker.internal
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - "5037:5037"
#    expose:
#      - "5037"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

  sender:
    container_name: ftp_sender
    build: .
    env_file: .env
    command: python3 ftp_sender.py
    volumes:
      - ./logs/ftp_sender:/app/logs
      - ./screenshots:/app/screenshots
    restart: always

  sender1:
    container_name: ftp_sender1
    build: .
    env_file: .env
    command: python3 ftp_sender_fake.py
    volumes:
      - ./logs/ftp_sender:/app/logs
      - ./screenshots:/app/screenshots
    restart: always


